import { asset } from "@/lib/utils";

// Drop-in replacement for next/image (which can't emit modern formats under
// `output: export` + unoptimized). Renders a <picture> with AVIF + WebP
// srcsets (generated by scripts/optimize-images.mjs into /images/optimized/)
// and the original JPEG as the universal <img> fallback.
//
// The <picture> uses display:contents so it adds no box of its own — the
// <img> lays out exactly as a bare next/image would, in both `fill`
// (absolute, object-cover) and intrinsic width/height modes.
//
// `src` is the RAW path, e.g. "/images/hero.jpeg" (asset() is applied here).

const VARIANT_WIDTHS = [384, 512, 768, 1280];

type OptimizedImageProps = {
  src: string;
  alt: string;
  className?: string;
  sizes?: string;
  fill?: boolean;
  width?: number;
  height?: number;
  priority?: boolean;
  ariaHidden?: boolean;
};

export function OptimizedImage({
  src,
  alt,
  className,
  sizes,
  fill = false,
  width,
  height,
  priority = false,
  ariaHidden,
}: OptimizedImageProps) {
  const file = src.slice(src.lastIndexOf("/") + 1);
  const name = file.slice(0, file.lastIndexOf("."));

  const srcSet = (ext: "avif" | "webp") =>
    VARIANT_WIDTHS.map(
      (w) => `${asset(`/images/optimized/${name}-${w}.${ext}`)} ${w}w`,
    ).join(", ");

  const fillStyle = fill
    ? ({ position: "absolute", inset: 0, height: "100%", width: "100%" } as const)
    : undefined;

  return (
    <picture style={{ display: "contents" }}>
      <source type="image/avif" srcSet={srcSet("avif")} sizes={sizes} />
      <source type="image/webp" srcSet={srcSet("webp")} sizes={sizes} />
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={asset(src)}
        alt={alt}
        aria-hidden={ariaHidden}
        className={className}
        sizes={sizes}
        width={fill ? undefined : width}
        height={fill ? undefined : height}
        loading={priority ? "eager" : "lazy"}
        fetchPriority={priority ? "high" : undefined}
        decoding="async"
        style={fillStyle}
      />
    </picture>
  );
}
